### ISSUE TITLE
'An error occurred while trying to upgrade BracketHighlighter. Please restart Sublime Text to finish the upgrade'

### ISSUE THREAD

**Issue by darkred** [facelessuser/BracketHighlighter#339]
_Using Sublime Text 3 build 3114 x64 stable in win10 x64._

I just tried updating BracketHighlighter from v2.14.1 to 2.14.2
via clicking Preferences|Package Control|Upgrade Package.

Unfortunately, a Package Control popup appeared that an error has happened.
Here is the relevant entries from console:

```
plugins loaded
SublimeLinter: debug mode: off 
Package Control: Installing 1 upgrades
ignored packages updated to: ["BracketHighlighter", "PackageResourceViewer", "SublimeLinter-jshint", "Vintage"]
unloading plugin BracketHighlighter.bh_core
reloading settings Packages/BracketHighlighter/bh_core.sublime-settings
unloading plugin BracketHighlighter.bh_logging
unloading plugin BracketHighlighter.bh_plugin
unloading plugin BracketHighlighter.bh_regions
unloading plugin BracketHighlighter.bh_remove
unloading plugin BracketHighlighter.bh_rules
unloading plugin BracketHighlighter.bh_search
unloading plugin BracketHighlighter.bh_swapping
unloading plugin BracketHighlighter.bh_wrapping
reloading settings Packages/User/Package Control.sublime-settings
Unable to decode Packages/BracketHighlighter/icons/double_quote_small.png
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Upgraded BracketHighlighter to 2.14.2
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["PackageResourceViewer", "SublimeLinter-jshint", "Vintage"]
reloading plugin BracketHighlighter.bh_core
reloading settings Packages/BracketHighlighter/bh_core.sublime-settings
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
error: Package Control

An error occurred while trying to upgrade BracketHighlighter. Please restart Sublime Text to finish the upgrade.

```

Then, after I restarted ST3 (and whenever I restart ST3),
here is what is shown in console:

```
plugins loaded
SublimeLinter: debug mode: off 
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_cleanup in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 77, in run
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Kostas\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\BracketHighlighter.sublime-package'
```

But, FWIW, there's no double ST3 process running, as I checked in Task Manager.

**Comment by facelessuser** [comment]
I am afraid this looks like a Package Control problem, not a BracketHighlighter problem.  I would try uninstalling BH and reinstalling via Package Control.

**Comment by darkred** [comment]
It was indeed a Package Control issue:
after uninstalling BH, and checking for updates,
a Package Control popup appeared that 
`1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.`.
So, after restarting ST3 and reinstalling BH, all is ok again.

Thanks for your reply!
