### ISSUE TITLE
(after upgrading from 2.14.3 to 2.15.0) "AppData\Roaming\SUBLIM~1\INSTAL~1\PACKAG~1.SUB\package_control\events.py", line 63, in do_clear KeyError: 'BracketHighlighter'

### ISSUE THREAD

**Issue by darkred** [facelessuser/BracketHighlighter#346]
Just upgrading BH from 2.14.3 to 2.15.0 )(using ST3 build 3114 x64 in win410x64)_
I got this in console:
```
Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\SUBLIM~1\INSTAL~1\PACKAG~1.SUB\package_control\events.py", line 63, in do_clear
KeyError: 'BracketHighlighter'
```

<br>
------
The whole log 
```
Package Control: Installing 1 upgrades
ignored packages updated to: ["BracketHighlighter", "PackageResourceViewer", "SublimeLinter-jshint", "Vintage"]
unloading plugin BracketHighlighter.bh_core
reloading settings Packages/BracketHighlighter/bh_core.sublime-settings
unloading plugin BracketHighlighter.bh_logging
unloading plugin BracketHighlighter.bh_plugin
unloading plugin BracketHighlighter.bh_regions
unloading plugin BracketHighlighter.bh_remove
unloading plugin BracketHighlighter.bh_rules
unloading plugin BracketHighlighter.bh_search
unloading plugin BracketHighlighter.bh_swapping
unloading plugin BracketHighlighter.bh_wrapping
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Upgraded BracketHighlighter to 2.15.0
ignored packages updated to: ["PackageResourceViewer", "SublimeLinter-jshint", "Vintage"]
reloading plugin BracketHighlighter.bh_core
reloading settings Packages/BracketHighlighter/bh_core.sublime-settings
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
ignored packages updated to: ["BracketHighlighter", "PackageResourceViewer", "SublimeLinter-jshint", "Vintage"]
unloading plugin BracketHighlighter.bh_core
reloading settings Packages/BracketHighlighter/bh_core.sublime-settings
unloading plugin BracketHighlighter.bh_logging
unloading plugin BracketHighlighter.bh_plugin
unloading plugin BracketHighlighter.bh_regions
unloading plugin BracketHighlighter.bh_remove
unloading plugin BracketHighlighter.bh_rules
unloading plugin BracketHighlighter.bh_search
unloading plugin BracketHighlighter.bh_swapping
unloading plugin BracketHighlighter.bh_wrapping
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["PackageResourceViewer", "SublimeLinter-jshint", "Vintage"]
reloading plugin BracketHighlighter.bh_core
reloading settings Packages/BracketHighlighter/bh_core.sublime-settings
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\SUBLIM~1\INSTAL~1\PACKAG~1.SUB\package_control\events.py", line 63, in do_clear
KeyError: 'BracketHighlighter'

```

**Comment by darkred** [comment]
I have the following keyboard shortcuts in `Preferences|Key Bindings - User`
```
[
	{ "keys": ["ctrl+keypad0"], "command": "reset_font_size" },

	// All 3 are for BracketHighlighter
    // Search to end of file for bracket
    {
        "keys": ["ctrl+alt+super+b"],
        "command": "bh_key",
        "args":
        {
            "lines" : true
        }
    },
	// Go to left bracket
    {
        "keys": ["ctrl+alt+super+up"],
        "command": "bh_key",
        "args":
        {
            "no_outside_adj": null,
            "lines" : true,
            "plugin":
            {
                "type": ["__all__"],
                "command": "bh_modules.bracketselect",
                "args": {"select": "left"}
            }
        }
    },
    // Go to right bracket
    {
        "keys": ["ctrl+alt+super+down"],
        "command": "bh_key",
        "args":
        {
            "no_outside_adj": null,
            "lines" : true,
            "plugin":
            {
                "type": ["__all__"],
                "command": "bh_modules.bracketselect",
                "args": {"select": "right"}
            }
        }
    },

]

```
Could they be related? But this has occured only after this update - never before

**Comment by facelessuser** [comment]
Did you see it again after restarting Sublime?  Sometimes after an update a restart is needed.

**Comment by darkred** [comment]
No, I don't see that error again, in any subsequent restarts. 
It must be that a restart was needed.
Thanks for answering

**Comment by facelessuser** [comment]
I figured that would be the case.  Glad it's working for you.
