### ISSUE TITLE
[BH 2.18.3] Errors in console related to loading bh_core and bh_rules. Also my BH keyboard shortcuts no longer work

### ISSUE THREAD

**Issue by darkred** [facelessuser/BracketHighlighter#352]
_Using ST3 build 3117  (in win10 x64) and BH 2.18.3._

Today after updating from ST3 from 3114 to 3117 
and BH from 2.17.0 to 2.18.3 (via Package Control)
I got these in console:
```
reloading plugin BracketHighlighter.bh_core
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 83, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 702, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_core in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 16, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 702, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_rules in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 7, in <module>
ImportError: No module named 'backrefs'
...
reloading plugin BracketHighlighter.bh_rules
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 83, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 702, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_rules in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 7, in <module>
ImportError: No module named 'backrefs'
```

For reference I removed+reinstalled BH 2.18.13 (always via Package Control)
but the entries appear every time I start ST3.

PS. The full console log while starting ST3: http://pastebin.com/raw/2wPbQPRL

---

Also, probably related, I noticed that the 3 keyboard shortcuts I have in 
`Preferences|Key Bindings|User (right panel)`
no longer work:
```
[
	{ "keys": ["ctrl+keypad0"], "command": "reset_font_size" },

	// All 3 are for BracketHighlighter
    // Search to end of file for bracket
    {
        "keys": ["ctrl+alt+super+b"],
        "command": "bh_key",
        "args":
        {
            "lines" : true
        }
    },
	// Go to left bracket
    {
        "keys": ["ctrl+alt+super+up"],
        "command": "bh_key",
        "args":
        {
            "no_outside_adj": null,
            "lines" : true,
            "plugin":
            {
                "type": ["__all__"],
                "command": "bh_modules.bracketselect",
                "args": {"select": "left"}
            }
        }
    },
    // Go to right bracket
    {
        "keys": ["ctrl+alt+super+down"],
        "command": "bh_key",
        "args":
        {
            "no_outside_adj": null,
            "lines" : true,
            "plugin":
            {
                "type": ["__all__"],
                "command": "bh_modules.bracketselect",
                "args": {"select": "right"}
            }
        }
    },

]
```

**Comment by facelessuser** [comment]
Try running the command pallette command `satisfy dependencies` and try restarting ST.

**Comment by darkred** [comment]
Unfortunately it didn't make any difference.

**Comment by darkred** [comment]
I just did that again (uninstall BH, restart ST3, reinstall BH)
and even ran `satisfy dependencies` after re-installing, but with the same result.

**Comment by facelessuser** [comment]
It is possible i interpreted how dependencies get load incorrectly.  I install backrefs if version is greater than version A, but I install other dependencies if greater than a later revision B.  I assumed that since the current version met both requirements that both sets would get installed, maybe that is not the case.  Maybe I need to specify backrefs in both dependency rules.  As I already had the dependencies, I probably didn't notice.

**Comment by facelessuser** [comment]
I'm working on a patch.

**Comment by facelessuser** [comment]
Release made.  When it drops, if it is still throwing errors, try satisfy dependencies again and restart.  Please let me know when if there are no issues.

**Comment by darkred** [comment]
The update is not available yet, but I noticed [in your latest commit](https://github.com/facelessuser/BracketHighlighter/commit/1a8ce443bbd7731150883b235c642d624eec789d) that backrefs is written as `backrfs`. 
Shouldn't it be `backrefs` instead as [in here](http://facelessuser.github.io/backrefs/installation/)?

**Comment by facelessuser** [comment]
I did it from my phone :(.

**Comment by facelessuser** [comment]
Okay, I fixed it.  Hopefully in the next hour or will drop.

**Comment by facelessuser** [comment]
It's available now

**Comment by darkred** [comment]
It's fixed. Thank you very much!
