### ISSUE TITLE
Error in JS file with show_offscreen_bracket_popup

### ISSUE THREAD

**Issue by pdanpdan** [facelessuser/BracketHighlighter#353]
When show_offscreen_bracket_popup: true I get the following error in console:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 246, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 427, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "bh_core in /home/pdan/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package", line 996, in on_hover
  File "bh_core in /home/pdan/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package", line 955, in show_popup
  File "bh_core in /home/pdan/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package", line 925, in guess_lang
TypeError: can only concatenate tuple (not "str") to tuple
```

- SubliemText version: 3117 linux x64 channel: dev

**Comment by facelessuser** [comment]
Run this from the console and tell what you see:

```
import mdpopups; mdpopups.version()
```

Anything less than `(1, 5, 0)` requires you to run the Package Control command `Satisfy Dependencies` (watch for it to complete in the console) and then a restart of Sublime Text.

**Comment by pdanpdan** [comment]
import mdpopups; mdpopups.version()
(1, 3, 4)

But now it's working as expected.
Thank you
