### ISSUE TITLE
Issue between BracketHighlighter and Material Theme packages

### ISSUE THREAD

**Issue by bagelbits** [facelessuser/BracketHighlighter#362]
### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description
I'm seeing any error when having both BracketHighlighter and Material Theme packages installed. It seems to be affecting functionality with Material Theme and may be affecting functionality with BracketHighlighter as well (though I haven't seen anything yet).

Running Material Theme v3.1.3 and BracketHighlighter v2.21.2

Related issue with Material Theme: https://github.com/equinusocio/material-theme/issues/931

Tracebacks in console look as follows:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "changes in /Users/zardoz/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 4, in <module>
  File "/Users/zardoz/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 19, in <module>
    from .st_scheme_template import Scheme2CSS, POPUP, PHANTOM
  File "/Users/zardoz/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 22, in <module>
    from pygments.formatters import HtmlFormatter
ImportError: No module named 'pygments'
```

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "material_theme in /Users/zardoz/Library/Application Support/Sublime Text 3/Installed Packages/Material Theme.sublime-package", line 5, in <module>
  File "/Users/zardoz/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 16, in <module>
    from . import version as ver
ImportError: cannot import name version
```

---

### Issue Support Info

- ST ver.:        3114
- Platform:       osx
- Arch:           x64
- Plugin ver.:    2.21.2
- Install via PC: True
- mdpopups ver.:  Version could not be acquired!
- backrefs ver.:  1.0.post1
- markdown ver.:  2.6.6
- pygments ver.:  1.6
- jinja2 ver.:    2.8

### Steps to Reproduce Issue

1. Install Material Theme
2. Install BracketHighlighter
3. Restart ST3 and look at console.

**Comment by facelessuser** [comment]
It actually has nothing to do with Material Theme.  I can see what the issue is.  Thank you for reporting.

**Comment by facelessuser** [comment]
New release was just made.  When available on Package Control, you should be able to upgrade.
