### ISSUE TITLE
Plugin Seems To Be Working, Unknown Traceback @ Console

### ISSUE THREAD

**Issue by Enteleform** [facelessuser/BracketHighlighter#397]
## Description

Plugin seems to be working fine, but there's a Traceback every minute or so that is cluttering my console.  
(*Tested with* `Global Enable` *both ON and OFF, issue occurs either way*)

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 620, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "bh_core in C:\Users\Fico\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 979, in on_hover
AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 620, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "bh_core in C:\Users\Fico\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 979, in on_hover
AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 620, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "bh_core in C:\Users\Fico\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 979, in on_hover
AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text\sublime_plugin.py", line 620, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "bh_core in C:\Users\Fico\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 979, in on_hover
AttributeError: 'list' object has no attribute 'get'
```

## Support Info

- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.23.1
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

Unclear, as the TraceBack occurs even while `Global Enable` is set to OFF

**Comment by facelessuser** [comment]
There's too issues here.

1.  Hover isn't disabled on global disable.

2. When we do global disable we incorrectly set locations to an empty list instead of an empty dict: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.py#L368.

So then we enter into the hover, when we shouldn't, and then access a list, when it should be a dict.

That's the story 😉 .

**Comment by Enteleform** [comment]
Haven't looked much into the new hover & phantoms features yet. What hover functionality do you have in BracketHighlighter?

The in-line color phantoms in ColorHelper are pretty awesome 😀

**Comment by r-stein** [comment]
If you hover over highlighted bracket and the matching bracket is offscreen, a popup will appear, which shows the text around the matching bracket and has a button to jump to the matching bracket.
