### ISSUE TITLE
(after upgrading from 2.23.1 to 2.23.2) ImportError: No module named 'yaml'

### ISSUE THREAD

**Issue by darkred** [facelessuser/BracketHighlighter#400]
During upgrading BH from 2.21.3 to 2.21.4 (using ST3 build 3126 x64 in win10 x64) I got: `An error occurred while trying to upgrade BracketHighlighter. Please restart Sublime Text to finish the upgrade`

Then, at ST3 restart, I'm getting this in console every time:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "spellcheck in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 6, in <module>
ImportError: No module named 'yaml'
```
I also tried uninstalling+reinstalling BH a few times, as well as pressing `Satisfy Dependencies` but the issue still occurs.

**Comment by facelessuser** [comment]
Ah...I know what's going on... :(.

Okay, I can fix that.  I added a test to check document spelling, but it's in the root, so Sublime tries to import it.  I need to move it out of the root or require yaml in dependencies.

**Comment by facelessuser** [comment]
[`st3-2.23.3`](https://github.com/facelessuser/BracketHighlighter/releases/tag/st3-2.23.3) has been released.  Let me know if (when available in Package Control) fixes your issue.

**Comment by darkred** [comment]
Yes, it's fixed now. Thanks

**Comment by Armour** [comment]
I just found this bug lol, thx!

**Comment by facelessuser** [comment]
Just thought I'd break everyone's workstation today :smile:.
