### ISSUE TITLE
Has an Conflict with OmniMarkupPreviewer

### ISSUE THREAD

**Issue by tobiashochguertel** [facelessuser/BracketHighlighter#416]
With BracketHighlighter and OmniMarkupPreviewer installed in Sublime Text 3, it's not possbile to run anylonger the OmniMarkupPreviewer Plugin. Can you have please a look at the following issue at [OmniMarkupPreviewer/issues/88](https://github.com/timonwong/OmniMarkupPreviewer/issues/88) which shows the exception trace from OmniMarkupPreviewer?

```
OmniMarkupPreviewer: [INFO] Bottle v0.11.6 server starting up...
OmniMarkupPreviewer: [INFO] Listening on http://127.0.0.1:51004/
OmniMarkupPreviewer: [INFO] Loaded renderer: AsciiDocRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: CreoleRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: MarkdownRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: MediaWikiRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: OrgRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: PodRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: RDocRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: RstRenderer
OmniMarkupPreviewer: [INFO] Loaded renderer: TextileRenderer
OmniMarkupPreviewer: [INFO] Reloading settings...
OmniMarkupPreviewer: [ERROR] Exception occured while rendering using MarkdownRenderer
  Traceback (most recent call last):
    File "C:\Users\hochguertelto\AppData\Roaming\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\RendererManager.py", line 266, in render_text
    rendered_text = renderer.render(text, filename=filename)
    File "C:\Users\hochguertelto\AppData\Roaming\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers/MarkdownRenderer.py", line 48, in render
    extensions=self.extensions)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\__init__.py", line 493, in markdown
    md = Markdown(*args, **kwargs)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\__init__.py", line 291, in build_extension
    return module.makeExtension(**configs)
    File "C:\Users\hochguertelto\AppData\Roaming\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers\libs\mdx_strikeout.py", line 17, in makeExtension
    return StrikeoutExtension(configs=configs)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\extensions\__init__.py", line 51, in __init__
    self.setConfigs(kwargs)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\extensions\__init__.py", line 82, in setConfigs
    self.setConfig(key, value)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\extensions\__init__.py", line 70, in setConfig
    if isinstance(self.config[key][0], bool):
  KeyError: 'configs'

OmniMarkupPreviewer: [INFO] Launching web browser for http://127.0.0.1:51004/view/29
OmniMarkupPreviewer: [ERROR] Exception occured while rendering using MarkdownRenderer
  Traceback (most recent call last):
    File "C:\Users\hochguertelto\AppData\Roaming\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\RendererManager.py", line 266, in render_text
    rendered_text = renderer.render(text, filename=filename)
    File "C:\Users\hochguertelto\AppData\Roaming\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers/MarkdownRenderer.py", line 48, in render
    extensions=self.extensions)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\__init__.py", line 493, in markdown
    md = Markdown(*args, **kwargs)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\__init__.py", line 291, in build_extension
    return module.makeExtension(**configs)
    File "C:\Users\hochguertelto\AppData\Roaming\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers\libs\mdx_strikeout.py", line 17, in makeExtension
    return StrikeoutExtension(configs=configs)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\extensions\__init__.py", line 51, in __init__
    self.setConfigs(kwargs)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\extensions\__init__.py", line 82, in setConfigs
    self.setConfig(key, value)
    File "C:\Users\HOCHGU~1\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\extensions\__init__.py", line 70, in setConfig
    if isinstance(self.config[key][0], bool):
  KeyError: 'configs
```

- Sublime Text 3, Version 3126
- Windows 10 Professional

**Comment by facelessuser** [comment]
I have had people come over here about this issue on OmniMarkupPreviewer before.  They continue vendoring their own Python Markdown and Pygments.  This might be because they support ST2, and recent Markdown versions drop Py2.6 support. Even if this is the case, I would accept a pull to support Py2.6 via pull request for at least for the last known working version on Py2.6 on the common Markdown dependency.  On top of that, OmniMarkupPreview also refuses to access the package relatively and instead imports its vendored version into sys.path.  That's were the common Markdown dependency is (which is the point of dependencies).  That is why there is a conflict.

If they continue to ship their own vendored libs, they need to switch to using them relatively instead of importing them into the global path, or switch to using the common dependency. BracketHighlighter is not the only package using the common Markdown dependency. If they must continuing supporting ST2, they can issue a pull to the dependency to add the last known working version for Py2.6, or even port existing versions of Markdown to Py2.6. Or stop importing theirs globally. I'm putting this issue fully on them.  Instead of fixing this they continue to allow people to do hacky workarounds: https://github.com/timonwong/OmniMarkupPreviewer/issues/85.

**Comment by facelessuser** [comment]
Closing as I vote this as an issue with their package.

**Comment by tobiashochguertel** [comment]
Hopefully some developer with python knowledge can fix the thing at OmniMarkupPreviewer and create there an pull request.
Okay. Thanks for pointing this out.

**Comment by facelessuser** [comment]
Yeah, I don't know any they do it the way they do. It requires everyone to use their​ version, and no packages can count on it being there.  With dependencies, you can require it, and count on it. And it is the same for everybody.

I can understand why you'd want to be locked to a single version. You don't have to worry about it changing and breaking on you. But you have to do it right so you don't break everyone else. Even if it requires modifying the package so it works in a relative manner.

Anyways.  I hope it does get fixed. You aren't the first to come to me about this
