### ISSUE TITLE
ImportError: cannot import name bre

### ISSUE THREAD

**Issue by chriscarpenter12** [facelessuser/BracketHighlighter#432]
## Description
On a new install I am getting this error in the console. Looks like an issue installing the `backrefs` module even though it reports it was installed...
ImportError: cannot import name bre

The package is creating the directory in my packages folder.
![screen shot 2017-09-01 at 9 24 06 am](https://user-images.githubusercontent.com/458486/29971754-74414932-8ef7-11e7-9f72-f798afa64bd9.png)

```
Package Control: The dependency 'backrefs' is not currently installed; installing...
Package Control: The dependency 'backrefs' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin BracketHighlighter.bh_core
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_core in /Users/chris/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 16, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_rules in /Users/chris/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 7, in <module>
ImportError: cannot import name bre
```

## Support Info

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.25.0
- Install via PC: True
- mdpopups ver.: Version could not be acquired!
- backrefs ver.: Version could not be acquired!
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Install BracketHighlighter from package control.
2. Watch console.
3.

**Comment by chriscarpenter12** [comment]
Ok seems to be fine after restarting. Thanks

**Comment by facelessuser** [comment]
The documentation mentions restarting after installing. Sometimes packages that load dependencies don't quite get everything loaded proper on install. In general, restarting Sublime is good advice after installing anything.
