### ISSUE TITLE
Changelog mdpopups error

### ISSUE THREAD

**Issue by stdedos** [facelessuser/BracketHighlighter#449]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request.

---

## Description

... what is the issue / request ?

On loading the Package Control Messages for the update I just received, I get 

```
BracketHighlighter
------------------

  # BracketHighlighter 2.26.0
  
  New release!
  
  Please see `Preferences->Package Settings->BracketHighlighter->Changelog`  
  for more info about the release.
```

Following the prompt, I see:

![image](https://user-images.githubusercontent.com/133706/32431917-1329af20-c2de-11e7-83c9-2b523ffde922.png)

```
mdpopups: Failed to convert/retrieve scheme to CSS!
mdpopups: Failed to get Sublime highlighter object!
mdpopups: Traceback (most recent call last):
  File "/home/sntentos/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 656, in add_phantom
    nl2br=nl2br, allow_code_wrap=allow_code_wrap
  File "/home/sntentos/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 329, in _create_html
    allow_code_wrap=allow_code_wrap
  File "/home/sntentos/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 447, in md2html
    ).convert(_markup_template(markup, template_vars, template_env_options)).replace('&quot;', '"').replace('\n', '')
  File "/home/sntentos/.config/sublime-text-3/Packages/python-markdown/st3/markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "/home/sntentos/.config/sublime-text-3/Packages/python-markdown/st3/markdown/treeprocessors.py", line 295, in run
    self.__handleInline(text), child
  File "/home/sntentos/.config/sublime-text-3/Packages/python-markdown/st3/markdown/treeprocessors.py", line 106, in __handleInline
    data, patternIndex, startIndex)
  File "/home/sntentos/.config/sublime-text-3/Packages/python-markdown/st3/markdown/treeprocessors.py", line 239, in __applyPattern
    node = pattern.handleMatch(match)
  File "/home/sntentos/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/inlinehilite.py", line 101, in handleMatch
    return self.highlight_code(lang, src)
  File "/home/sntentos/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/inlinehilite.py", line 85, in highlight_code
    ).highlight(src, language, self.css_class, inline=True)
  File "/home/sntentos/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 324, in highlight
    code = self.sublime_hl[1].syntax_highlight(
AttributeError: 'NoneType' object has no attribute 'syntax_highlight'
```

## Support Info

```
- ST ver.: 3143
- Platform: linux
- Arch: x64
- Plugin ver.: 2.26.0
- Install via PC: True
- mdpopups ver.: 3.0.3
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

## Steps to Reproduce Issue

1. GoTo: Description
2. (i.e. open changelog)

**Comment by facelessuser** [comment]
You need the latest mdpopups.  Run `Package Control: Satisfy dependencies`, check console to ensure it finishes, then restart Sublime.

**Comment by stdedos** [comment]
```Package Control: All dependencies have been satisfied```
 :/

**Comment by facelessuser** [comment]
Restart Sublime and run the command again. 3.1.1 is the latest mdpopups.

**Comment by stdedos** [comment]
I have already done that before posting

**Comment by facelessuser** [comment]
I'll try on a portable Sublime when I get into work in the next hour or so. I'm running my dev channel, so I always get the tip. I need to check if package control is pulling the most recent tag for normal users.

**Comment by facelessuser** [comment]
Okay, I installed a new clean portable version and it pulled mdpopups 3.1.1.  So you have a local Package Control issue.  So now I'll suggest some more aggressive options.

1. Exit Sublime Text
2. Delete mdpopups folder in your Packages folder.
3. Start Sublime Text.  Package Control should install mdpopups fresh (check console).
4. Restart Sublime Text.

**Comment by facelessuser** [comment]
If with the above steps it doesn't auto install the missing dependency, run `Satisfy dependencies` and then restart.

**Comment by stdedos** [comment]
Nuking `mdpopus` works.

Question: Do "you" control final cursor location?
Loading Changelog I see this
![image](https://user-images.githubusercontent.com/133706/32484319-09027782-c3a8-11e7-9b75-c6925b15bc09.png)
