### ISSUE TITLE
error on widget view

### ISSUE THREAD

**Issue by randy3k** [facelessuser/BracketHighlighter#488]
## Description

Got the following error while in a [Terminus](https://github.com/randy3k/Terminus) view
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 462, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 701, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "/Users/Randy/Dropbox/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 992, in on_hover
    for k, v in locations.get('unmatched', {}).items():
AttributeError: 'list' object has no attribute 'get'
```

Terminus view is basically a widget.
For some reasons unknown,
BH thinks that it is a clone view so that `view.settings().get("bracket_highlighter.clone") == view.id()`. The [location_key](https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.py#L990) therefore is `bracket_highlighter.clone_locations` and 
```
>>> view.settings().get("bracket_highlighter.clone_locations", {})
[]
```
is a list which results the error.

### Another thing that I notice

Should [this line](https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.py?utf8=✓#L791) be
```
locations_key = 'bracket_highlighter.clone_locations' if clone_view else 'bracket_highlighter.locations'
```
in the same essence of line 990?

## Support Info

- ST ver.: 3175
- Platform: osx
- Arch: x64
- Plugin ver.: 2.27.4
- Install via PC: True
- mdpopups ver.: 3.3.3
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

Open Terminus Terminal in a view and hover on some text (it may take a few trials to trigger the error).

**Comment by randy3k** [comment]
Even setting `bracket_highlighter.ignore` does not disable `on_hover` to run.

**Comment by facelessuser** [comment]
I know the location implementation changed a couple times in development, most likely I missed some things.

As the hover was bolted on later, it looks like I forgot to add support for ignore...

Yeah, I'll have to take a look at this and sort it out.

**Comment by randy3k** [comment]
The default value for [bracket_highlighter.clone_locations][1] should be a dict.


[1]: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.py#L1051-L1059

**Comment by facelessuser** [comment]
Yeah, there are some issues with hover events and clone views as well.  This isn't working how I remember it working... it appears hover events only work currently for clone views where the brackets were highlighted in the original non-cloned view.  When testing, I must have been comparing the same brackets in both views, but didn't try and other brackets in the clone view.

Ugh.  Clones were tricky to get recognized properly, but there appears to be more work to get hovers working properly.  Anyways, I'll look more into this when I get back.

**Comment by facelessuser** [comment]
I have some fixes in for some of these issues.  I don't expect this will fix all the clone related issues, but at least the errors you were seeing: list/dict error, on_hover issue, etc.  I know this is way later than I originally said, but better late than never.
