### ISSUE TITLE
Manual Installation is outdated/broken for 3.0.3143?

### ISSUE THREAD

**Issue by Kein** [facelessuser/BracketHighlighter#521]
https://facelessuser.github.io/BracketHighlighter/installation/

Sublime 3.0.3143/Windows 7

Steps 1-2 were no issue. Step 3 made no sense, `Create a folder under Packages`, what does under means? Inside the `Packages`? Alongside the `Packages`? Same for the py script. Either way I just went for both assumptions and made a bunch of `00-dependencies ` and `00-dependencies.py` everywhere.

Console output: 
```
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 00-dependencies
reloading plugin 00-dependencies.00-dependencies
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1519, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\SublimeText\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1522, in _find_and_load_unlocked
ImportError: No module named '00-dependencies.00-dependencies'; 00-dependencies is not a package
reloading plugin BracketHighlighter.bh_core
Traceback (most recent call last):
  File "C:\Programs\SublimeText\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\BracketHighlighter\bh_core.py", line 16, in <module>
    import BracketHighlighter.bh_rules as bh_rules
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\BracketHighlighter\bh_rules.py", line 7, in <module>
    from backrefs import bre
ImportError: cannot import name bre
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
Traceback (most recent call last):
  File "C:\Programs\SublimeText\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\UserName\AppData\Roaming\Sublime Text 3\Packages\BracketHighlighter\bh_rules.py", line 7, in <module>
    from backrefs import bre
ImportError: cannot import name bre
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
plugins loaded

```

**Comment by facelessuser** [comment]
Normally, **under**, when dealing with folders, means **inside**. 

As far as I am aware, there are a number of people who do use manual installation, so I am pretty confident the approach generally works.

With all of that said, BracketHighlighter is meant to be installed via PackageControl. If you have desire to install manually, and you are having issues, you will have to provide me detailed step by step of **exactly** what you did so I can advise. I don't want to have to guess, or spend a lot of time trying to figure out exactly what you may or may not be doing. I don't really offer much support when dealing with manual installations as that is not the expected way for it to be used, even if it is technically possible. But if there is something obvious, I'll be more than happy to help point it out.

**Comment by Kein** [comment]
PackageControl does not work for me.
All the details in the post, I did exactly what the Installation page said.

**Comment by facelessuser** [comment]
The only thing missing from the documentation was pyyaml. Install from https://github.com/packagecontrol/pyyaml as `pyyaml`

And make sure the `00-dependencies.py` script includes `pyyaml` as well. I load it first in this case :

```py
add_dependency('pyyaml')
add_dependency('pygments')
add_dependency('backrefs')
add_dependency('markupsafe')
add_dependency('python-markdown')
add_dependency('python-jinja2')
add_dependency('mdpopups')
```

If you are still having issues, it is most likely because you've  some how installed one of the dependencies incorrectly, or have some how created the `00-dependencies` package incorrectly. I've tested this on the latest sublime public release, and it worked fine. I will update the documentation accordingly.

If you are still having issues, please provide exact details of what you did as I've done exactly what was in the documentation and had no issues. If the issue is specific to build 3134, then you may need to upgrade.

**Comment by Kein** [comment]
This is what I get if I install `pyyaml` the way you say:
https://hastebin.com/qoxoluqupa.sql

This is what I get if I just drop it as `yaml`
https://hastebin.com/hosadohesa.sql

These issues getting weirder and weirder

**Comment by facelessuser** [comment]
Unfortunately, it worked perfect for me. Order of import is important. Can you post what order you import the dependencies in?

Other than that, I have no way to inspect your environment and double check that things are as they should be. I can only tell you that it worked with no issues for me. Make sure the folder structure of each dependency looks right, and make sure 00-dependencies imports them in the order I posted I'm my last response.

**Comment by Kein** [comment]
Alright, nevermind, I will just drop it for now, thanks for the tips.
