### ISSUE TITLE
BracketHighlighter related issues: mdpopups: Failed to convert/retrieve scheme to CSS!

### ISSUE THREAD

**Issue by hongyi-zhao** [facelessuser/BracketHighlighter#530]
Hi here,

I manually installed the BracketHighlighter package for st3 according the instructions here:

https://facelessuser.github.io/BracketHighlighter/installation/

But when I start the st3, it will give error as follows in the console:

-----------------------
mdpopups: Failed to convert/retrieve scheme to CSS!
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 717, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "/home/werner/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 1020, in on_hover
    bh_popup.BhOffscreenPopup().show_popup(view, point, region, icon)
  File "/home/werner/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_popup.py", line 302, in show_popup
    markup = self.get_markup(view, point, region, icon)
  File "/home/werner/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_popup.py", line 243, in get_markup
    color = mdpopups.scope2style(view, icon[1]).get('color')
  File "/home/werner/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 544, in scope2style
    style_obj = obj.guess_style(view, scope, selected, explicit_background)
AttributeError: 'NoneType' object has no attribute 'guess_style'
-----------------------

Any hints?

Regards

**Comment by facelessuser** [comment]
It is difficult for me to be sure. My only advise is to make sure you install the dependencies from the latest tagged release. If you grab from the main line, you may get code not meant for release yet.

**Comment by facelessuser** [comment]
While it is possible to manually install BH, we don't formally offer much support and troubleshooting for it except for what is mentioned in the documentation.
