### ISSUE TITLE
BracketHighlighter failing to load

### ISSUE THREAD

**Issue by CuriousPhilomath** [facelessuser/BracketHighlighter#537]
## Description
I'm running SublimeText 3, Build 3207, on Linux.

This afternoon, I noticed that I wasn't seeing any bracket highlighting.

I checked the console and discovered that BracketHighlighter had been updated to version 2.27.7, and that it is failing to load. It feels like the two events are connected, since I was getting highlights earlier today.

Here is the relevant info (I hope) from the ST3 console:

```
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
 [ irrelevant lines (i.e. from other packages) snipped; available if needed ]
BracketHighlighter: Match object loaded.
 [ irrelevant lines snipped; available if needed ]
BracketHighlighter: Bracket Pattern: (curly,round,square)
    (Opening|Closing):     (?:(\{)|(\})|(\()|(\))|(\[)|(\]))

BracketHighlighter: SubBracket Pattern: (curly,round,square)
    (Opening|Closing): (?:(\{)|(\})|(\()|(\))|(\[)|(\]))

BracketHighlighter: Scope Regex (single_quote)
    Opening: \A(')
    Closing: (')\Z

BracketHighlighter: Scope Regex (double_quote)
    Opening: \A(")
    Closing: (")\Z

BracketHighlighter: Scope Regex (backtick_quote)
    Opening: \A(`)
    Closing: (`)\Z

BracketHighlighter: Scope Regex (jsregex)
    Opening: \A *(/)
    Closing: (/)[igm]*\Z

 [ irrelevant lines snipped; available if needed ]
ignored packages updated to: ["BracketHighlighter", "Vintage"]
unloading plugin BracketHighlighter.bh_core
reloading settings Packages/BracketHighlighter/bh_core.sublime-settings
unloading plugin BracketHighlighter.bh_logging
unloading plugin BracketHighlighter.bh_plugin
unloading plugin BracketHighlighter.bh_popup
unloading plugin BracketHighlighter.bh_regions
unloading plugin BracketHighlighter.bh_remove
unloading plugin BracketHighlighter.bh_rules
unloading plugin BracketHighlighter.bh_search
unloading plugin BracketHighlighter.bh_swapping
unloading plugin BracketHighlighter.bh_wrapping
Unable to decode Packages/BracketHighlighter/icons/curly_bracket_close_small.png
unloading plugin BracketHighlighter.support
 [ irrelevant lines snipped; available if needed ]
Package Control: Upgraded BracketHighlighter to 2.27.7
ignored packages updated to: ["Vintage"]
reloading plugin BracketHighlighter.bh_core
BracketHighlighter: Match object loaded.
reloading settings Packages/BracketHighlighter/bh_core.sublime-settings
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
 [ NOTE: home dir replaced with '~' for ease of reading ]
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 1145, in payload
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 406, in match
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 140, in init_match
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 127, in refresh_rules
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_rules.py", line 206, in load_rules
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_rules.py", line 257, in parse_bracket_definition
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_logging.py", line 19, in debug
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

The above error occurs a few more times in the console, but the later occurrences are preceded by a 'Key Event':
```
BracketHighlighter: Key Event
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 896, in run
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 902, in execute
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 406, in match
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 140, in init_match
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_core.py", line 127, in refresh_rules
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_rules.py", line 206, in load_rules
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_rules.py", line 257, in parse_bracket_definition
  File "~/.config/sublime-text-3/Installed Packages/BracketHighlighter.sublime-package/bh_logging.py", line 19, in debug
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

## Support Info

```
- ST ver.: 3207
- Platform: linux
- Arch: x64
- Plugin ver.: 2.27.7
- Install via PC: True
- mdpopups ver.: 3.4.0
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

## Steps to Reproduce Issue

1. I ran ST3, and saw no highlighting. Checked the console and discovered the attached errors.

**Comment by CuriousPhilomath** [comment]
Today I noticed that the problem had gone away. Not really sure what happened. Feel free to close this issue, I guess. Sorry if I caused any problems.

**Comment by facelessuser** [comment]
@CuriousPhilomath, sorry I didn't get to this until now, but after an update, you may need to restart Sublime Text. This is advisable when any plugin updates. Sometimes it isn't necessary, but complex plugins may require one if you start to see issues.
