### ISSUE TITLE
BrackerHighlighter - Quick Start doesn't open in ST 4074

### ISSUE THREAD

**Issue by oconnor0** [facelessuser/BracketHighlighter#550]
## Description

I just installed Bracket Highlighter and open the Quick Start. 

I get the following error:

![image](https://user-images.githubusercontent.com/64384/81866179-11ebff00-952c-11ea-8627-27ea65ca8d96.png)

The following is listed in the console:

```
mdpopups: Traceback (most recent call last):
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\__init__.py", line 664, in add_phantom
    nl2br=nl2br, allow_code_wrap=allow_code_wrap
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\__init__.py", line 328, in _create_html
    allow_code_wrap=allow_code_wrap
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\__init__.py", line 441, in md2html
    ).convert(_markup_template(markup, template_vars, template_env_options)).replace('&quot;', '"').replace('\n', '')
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\st3\markdown\core.py", line 265, in convert
    self.lines = prep.run(self.lines)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pymdownx\st3\pymdownx\superfences.py", line 737, in run
    return self.search_nested(lines)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pymdownx\st3\pymdownx\superfences.py", line 601, in search_nested
    self.eval_fence(ws, content, start, end)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pymdownx\st3\pymdownx\superfences.py", line 407, in eval_fence
    self.process_nested_block(ws, content, start, end)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pymdownx\st3\pymdownx\superfences.py", line 451, in process_nested_block
    code = entry["formatter"](self.rebuild_block(self.code), self.lang, self.options, self.md)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pymdownx\st3\pymdownx\superfences.py", line 666, in highlight
    linespecial=linespecial
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\mdx\highlight.py", line 450, in highlight
    code = highlight(src, lexer, formatter)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pygments\all\pygments\__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pygments\all\pygments\__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pygments\all\pygments\formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\pygments\all\pygments\formatters\html.py", line 831, in format_unencoded
    source = self.wrap(source, outfile)
  File "C:\Users\MATTHE~1.OCO\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\mdx\highlight.py", line 240, in wrap
    return self._wrap_code(self, source)
TypeError: _wrap_code() takes 2 positional arguments but 3 were given
```

## Support Info

```
- ST ver.: 4074
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.9
- Install via PC: True
- mdpopups ver.: 3.7.1
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1
```

**Comment by facelessuser** [comment]
Did you restart Sublime after installing?

**Comment by facelessuser** [comment]
![sublime_text_HUY5IQF8RY](https://user-images.githubusercontent.com/1055125/81866779-efa6b100-952c-11ea-9217-4d807a13d912.png)

**Comment by oconnor0** [comment]
I did not restart Sublime after installing. I immediately opened the Preferences > Package Settings > Bracket Highlighter > Quick Start as mentioned in the install log.

**Comment by facelessuser** [comment]
You should restart.

**Comment by facelessuser** [comment]
The way packages and dependencies get installed, restarting is usually best. I guess I should say that in the install log...

**Comment by facelessuser** [comment]
I'm assuming this resolved after restart?

**Comment by oconnor0** [comment]
I haven't had a chance to look at it yet.

**Comment by oconnor0** [comment]
Restarting allowed the Quick Start to open.

**Comment by oconnor0** [comment]
Should I be able to select the text in the Quick Start?

**Comment by facelessuser** [comment]
Nope. That is a limitation of Sublime's minihtml.

**Comment by oconnor0** [comment]
I guess this can be closed unless you want to leave it open to track the documentation change?

**Comment by facelessuser** [comment]
I'll leave it open for documentation. People run into this frequent enough that I should probably update the install message. The docs themselves do mention restarting, but people rarely look there.
