### ISSUE TITLE
Doesn't work on Android Studio Flamingo

### ISSUE THREAD

**Issue by mustafaozhan** [facelessuser/BracketHighlighter#609]
After enabling the plugin and restarting Android Studio having following exception, and the plugin is disabled automatically
```
Plugin 'io.github.qeesung.component.HighlightBracketPair' failed to initialize and will be disabled. Please restart Android Studio.

java.lang.ClassNotFoundException: 
                io.github.qeesung.component.HighlightBracketPairApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=HighlightBracketPair, id=io.github.qeesung.component.HighlightBracketPair, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4345.14.2221.9178080/Android Studio Preview.app.plugins/HighlightBracketPair, version=1.1.2, package=null, isBundled=false), packagePrefix=null, instanceId=12, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:214)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:449)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:370)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:55)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:251)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt:148)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
    at com.intellij.idea.ApplicationLoader$initApplication$block$2.execute(ApplicationLoader.kt:142)
    at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
    ```
    
    Here is the info about the android studio, not only version actually it didn't work with all the Flamingo versions
    ```
    Android Studio Flamingo | 2022.2.1 Canary 5
Build #AI-222.4345.14.2221.9178080, built on October 14, 2022
Runtime version: 17.0.4.1+0-17.0.4.1b469.62-9127311 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6a737d
    ide.editor.tab.selection.animation=true
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6a737d

Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    net.vektah.codeglance (1.5.4)
    detekt (1.21.3)
    com.intellij.marketplace (222.4345.24)
    YAML/Ansible support (0.11.2)
    Key Promoter X (2022.3)
    org.jetbrains.kotlin-js-inspection-pack-plugin (0.0.10)
    com.mallowigi (80.1.0)
    com.developerphil.adbidea (1.6.8)
    com.suusan2go.kotlin-fill-class (1.0.15)
    com.jetbrains.kmm (0.3.4(222-1.7.20-198-IJ)-184)
    com.chrisrm.idea.MaterialThemeUI (7.13.2)

```

**Comment by facelessuser** [comment]
BracketHighlighter is a Sublime Text plugin, not an Android Studio plugin.

**Comment by facelessuser** [comment]
I'm assuming there is a similar named plugin fro Android Studio and you mistakenly came here. Either way, there is no actionable item for us here.
