### ISSUE TITLE
HTML tag highlighting stopped working

### ISSUE THREAD

**Issue by Aslanex** [facelessuser/BracketHighlighter#640]
## Description

HTML tag highlighting stopped working a few days ago. Other highlights work fine.

This is the error in Sublime Console:
```

BracketHighlighter: Could not load module bh_modules.tags
Traceback (most recent call last):
  File "/home/aslanex/.config/sublime-text/Installed Packages/BracketHighlighter.sublime-package/bh_plugin.py", line 75, in load_modules
    module = _import_module(plib, loaded)
  File "/home/aslanex/.config/sublime-text/Installed Packages/BracketHighlighter.sublime-package/bh_plugin.py", line 105, in _import_module
    exec(
  File "bh_modules.tags", line 29, in <module>
TypeError: namedtuple() got an unexpected keyword argument 'verbose'

BracketHighlighter: namedtuple() got an unexpected keyword argument 'verbose'
```

Here a screenshot of working BracketHighlighter:
![Snímek obrazovky z 2024-11-20 13-16-56](https://github.com/user-attachments/assets/da8b6836-61c8-486c-8ad8-15bd8eee3ba9)

Here the not working highlighter on tags:
![Snímek obrazovky z 2024-11-20 13-17-04](https://github.com/user-attachments/assets/c5f23d7b-2281-4918-a6db-28412a8f653d)

## Support Info

- ST ver.: 4180
- Platform: linux
- Arch: x64
- Plugin ver.: 2.32.0
- Install via PC: True
- mdpopups ver.: 4.2.2
- backrefs ver.: 5.5.1
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

Just open SublimeText.

**Comment by facelessuser** [comment]
This likely got missed when we opted into Python 3.8. That parameter should have been removed before the release. It's a trivial fix though. Thanks for reporting!

**Comment by facelessuser** [comment]
I've issue a fix and a release. It may take some time for Package Control to see it though, so give it time.
